### ISSUE TITLE
ImportError: cannot import name conninfo_encoding

### ISSUE THREAD

**Issue by iolbr** [psycopg/psycopg#206]
On amazonlinux I did a 
```pip install psycopg-binary```
After successfull install I started my python file. Got the following error:
```
(.venv) bash-4.2# ./classify_jobs.sh 
Traceback (most recent call last):
  File "jobmonkey/classificationmonkey.py", line 7, in <module>
    from model import Model, DATA
  File "/home/jobmonkey/jobmonkeyus/jobmonkey/model.py", line 6, in <module>
    from jobmonkey.dal.db import DataAccessLayer
  File "/home/jobmonkey/jobmonkeyus/jobmonkey/dal/db.py", line 2, in <module>
    import psycopg
  File "/home/jobmonkey/jobmonkeyus/.venv/lib/python3.8/site-packages/psycopg/__init__.py", line 11, in <module>
    from . import postgres
  File "/home/jobmonkey/jobmonkeyus/.venv/lib/python3.8/site-packages/psycopg/postgres.py", line 9, in <module>
    from ._adapters_map import AdaptersMap
  File "/home/jobmonkey/jobmonkeyus/.venv/lib/python3.8/site-packages/psycopg/_adapters_map.py", line 14, in <module>
    from ._cmodule import _psycopg
  File "/home/jobmonkey/jobmonkeyus/.venv/lib/python3.8/site-packages/psycopg/_cmodule.py", line 19, in <module>
    from psycopg_binary import _psycopg  # type: ignore
  File "psycopg_binary/_psycopg/generators.pyx", line 16, in init psycopg_binary._psycopg
ImportError: cannot import name conninfo_encoding
```
Any idea what is going wrong?

**Comment by dvarrazzo** [comment]
> pip install `psycopg-binary`

this is not the way to install psycopg 3. Installation instructions are at https://www.psycopg.org/psycopg3/docs/basic/install.html

You probably want `pip install psycopg[binary]`.
