### ISSUE TITLE
bug: psycopg_pool.PoolTimeout after success connection

### ISSUE THREAD

**Issue by andruche** [psycopg/psycopg#218]
Hey!
Maybe I'm doing something wrong, but it looks like a bug.

How to reproduce:
$ cat psycopg_pool_test.py
```py
import asyncio
from psycopg_pool import AsyncConnectionPool


async def sql_execute(pool, query):
    async with pool.connection() as con:
        print(f'start: {id(con)}')
        async with con.cursor() as cur:
            await cur.execute(query)
        print(f'done:  {id(con)}')

async def test():
    async with AsyncConnectionPool('dbname=test',
                                   kwargs={"autocommit": True},
                                   min_size=2,
                                   max_size=2,
                                   timeout=5) as pool:
        await asyncio.gather(*[sql_execute(pool, 'select pg_sleep(2)')
                               for i in range(12)])

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```
$ time python3.9 psycopg_pool_test.py
```log
start: 4331208368
start: 4331206880
done:  4331208368
done:  4331206880
start: 4331208368
start: 4331206880
done:  4331208368
done:  4331206880
start: 4331208368
start: 4331206880
Traceback (most recent call last):
  File "/Users/andrey/projects/bi_storage_meta/etl/psycopg_pool_test.py", line 22, in <module>
    loop.run_until_complete(test())
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/andrey/projects/bi_storage_meta/etl/psycopg_pool_test.py", line 18, in test
    await asyncio.gather(*[sql_execute(pool, 'select pg_sleep(2)')
  File "/Users/andrey/projects/bi_storage_meta/etl/psycopg_pool_test.py", line 6, in sql_execute
    async with pool.connection() as con:
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/opt/homebrew/lib/python3.9/site-packages/psycopg_pool/pool_async.py", line 111, in connection
    conn = await self.getconn(timeout=timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/psycopg_pool/pool_async.py", line 168, in getconn
    conn = await pos.wait(timeout=timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/psycopg_pool/pool_async.py", line 581, in wait
    raise self.error
psycopg_pool.PoolTimeout: couldn't get a connection after 5 sec

real	0m5.254s
user	0m0.119s
sys	0m0.028s
```
So the two connections (id: 4331208368, 4331206880) work correctly until suddenly a psycopg_pool.PoolTimeout exception raises after 5 seconds.

OS: macOS Monterey (12.0.1)
python-3.9
psycopg-3.0.8
psycopg-pool-3.0.3

**Comment by dvarrazzo** [comment]
Hello,

it seems that it working as expected. When you start your 12 processes, all of them ask for a connection. Two of them get one, 10 get queued. The timeout happens because some of the queued ones cannot get a connection within 5 seconds from the moment they get queued.

Changing a bit your test, into:
```python
import asyncio
import logging

from psycopg_pool import AsyncConnectionPool, PoolTimeout

logger = logging.getLogger()
logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')

async def sql_execute(pool, query, i):
    logger.info(f'asking {i}')
    try:
        async with pool.connection() as con:
            logger.info(f'start {i}: {id(con)}')
            async with con.cursor() as cur:
                await cur.execute(query)
            logger.info(f'done {i}:  {id(con)}')
    except PoolTimeout as e:
        logger.info(f"timeout {i}")

async def test():
    async with AsyncConnectionPool('',
                                   kwargs={"autocommit": True},
                                   min_size=2,
                                   max_size=2,
                                   timeout=5) as pool:
        await asyncio.gather(*[sql_execute(pool, 'select pg_sleep(2)', i)
                               for i in range(12)])

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```

a sample output is
```
2022-02-02 11:57:02,529 INFO asking 0
2022-02-02 11:57:02,529 INFO asking 1
2022-02-02 11:57:02,529 INFO asking 2
2022-02-02 11:57:02,529 INFO asking 3
2022-02-02 11:57:02,530 INFO asking 4
2022-02-02 11:57:02,530 INFO asking 5
2022-02-02 11:57:02,530 INFO asking 6
2022-02-02 11:57:02,530 INFO asking 7
2022-02-02 11:57:02,530 INFO asking 8
2022-02-02 11:57:02,530 INFO asking 9
2022-02-02 11:57:02,530 INFO asking 10
2022-02-02 11:57:02,530 INFO asking 11
2022-02-02 11:57:02,531 INFO start 0: 140292923190000
2022-02-02 11:57:02,531 INFO start 1: 140292923190480
2022-02-02 11:57:04,534 INFO done 0:  140292923190000
2022-02-02 11:57:04,535 INFO done 1:  140292923190480
2022-02-02 11:57:04,536 INFO start 2: 140292923190000
2022-02-02 11:57:04,537 INFO start 3: 140292923190480
2022-02-02 11:57:06,540 INFO done 3:  140292923190480
2022-02-02 11:57:06,541 INFO done 2:  140292923190000
2022-02-02 11:57:06,542 INFO start 4: 140292923190480
2022-02-02 11:57:06,543 INFO start 5: 140292923190000
2022-02-02 11:57:07,532 INFO timeout 6
2022-02-02 11:57:07,532 INFO timeout 7
2022-02-02 11:57:07,533 INFO timeout 8
2022-02-02 11:57:07,533 INFO timeout 9
2022-02-02 11:57:07,533 INFO timeout 10
2022-02-02 11:57:07,534 INFO timeout 11
2022-02-02 11:57:08,544 INFO done 4:  140292923190480
2022-02-02 11:57:08,546 INFO done 5:  140292923190000
```
as you can see, the worker 6 times out 5 seconds after it was queued.

Did you expect a different behaviour?

**Comment by andruche** [comment]
Thanks for the explanation, now I understand how it works.
I was just expecting that the timeout parameter in the pool constructor is just a timeout for a network connection like socket.settimeout()

These are different situations for me: when the pool can't connect to postgres, I want to stop waiting after 5 seconds and print an exception, but when the pool is connected to postgres and my tasks are being processed in parallel, I don't want to stop running.

I looked at the documentation ([here](https://www.psycopg.org/psycopg3/docs/api/pool.html#the-asyncconnectionpool-class)) and found the "open" method, which, according to the name, does exactly what I needed:
"async open(wait=False, timeout=30.0)"
But it doesn't exist (((

```py
import asyncio
import logging

from psycopg_pool import AsyncConnectionPool, PoolTimeout

logger = logging.getLogger()
logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')

async def sql_execute(pool, query, i):
    logger.info(f'asking {i}')
    try:
        async with pool.connection() as con:
            logger.info(f'start {i}: {id(con)}')
            async with con.cursor() as cur:
                await cur.execute(query)
            logger.info(f'done {i}:  {id(con)}')
    except PoolTimeout as e:
        logger.info(f"timeout {i}")

async def test():
    async with AsyncConnectionPool('dbname=test',
                                   kwargs={"autocommit": True},
                                   min_size=2,
                                   max_size=2,
                                   timeout=9999999) as pool:
        await pool.open(wait=True, timeout=5)
        await asyncio.gather(*[sql_execute(pool, 'select pg_sleep(2)', i)
                               for i in range(12)])

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```

```log
Traceback (most recent call last):
  File "/Users/andrey/projects/bi_storage_meta/etl/psycopg_pool_test.py", line 31, in <module>
    loop.run_until_complete(test())
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/andrey/projects/bi_storage_meta/etl/psycopg_pool_test.py", line 26, in test
    await pool.open(wait=True, timeout=5)
AttributeError: 'AsyncConnectionPool' object has no attribute 'open'
```

**Comment by dvarrazzo** [comment]
Yes, wait is to be introduced in psycopg-pool 3.1, which I should release in a few days.

You can use [`await pool.wait(timeout=5.0)`](https://www.psycopg.org/psycopg3/docs/api/pool.html#psycopg_pool.ConnectionPool.wait) for the same effect.

**Comment by andruche** [comment]
Ok, thanks)
