### ISSUE TITLE
Pool fails to fill when logger is at debug level

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#230]
This is weird.

If the `psycopg` logger is set to DEBUG level, connections are not created and `wait()` fails. The following script reproduces the input. Tested with `psycopg_pool==3.1` and pretty much [platform independent](https://github.com/psycopg/psycopg/actions/runs/1869106167).

The following script reproduces the issue:

```python
import logging
import psycopg_pool

logging.basicConfig(level=logging.DEBUG)
logging.getLogger("psycopg").setLevel(logging.DEBUG)

with psycopg_pool.ConnectionPool("", min_size=4) as p:
    try:
        p.wait(timeout=2)
    finally:
        print(p.get_stats())
```

The script most often fails with the following output, meaning that no connection was completed:

<details>

```
DEBUG:psycopg.pool:task created in MainThread: <AddConnection 'pool-1' at 0x7efe16029ee0>
DEBUG:psycopg.pool:task created in MainThread: <AddConnection 'pool-1' at 0x7efe1602f3a0>
DEBUG:psycopg.pool:task created in MainThread: <AddConnection 'pool-1' at 0x7efe1602f400>
DEBUG:psycopg.pool:task created in MainThread: <AddConnection 'pool-1' at 0x7efe1602f460>
DEBUG:psycopg.pool:task created in MainThread: <ShrinkPool 'pool-1' at 0x7efe1602f2e0>
INFO:psycopg.pool:waiting for pool 'pool-1' initialization
DEBUG:psycopg.pool:pool 'pool-1' closed
DEBUG:psycopg.pool:task created in MainThread: <StopWorker 'pool-1' at 0x7efe1602f580>
DEBUG:psycopg.pool:task created in MainThread: <StopWorker 'pool-1' at 0x7efe1602f610>
DEBUG:psycopg.pool:task created in MainThread: <StopWorker 'pool-1' at 0x7efe1602f670>
DEBUG:psycopg.pool:terminating working thread pool-1-worker-1
DEBUG:psycopg.pool:terminating working thread pool-1-worker-2
DEBUG:psycopg.pool:terminating working thread pool-1-worker-0
{'pool_min': 4, 'pool_max': 4, 'pool_size': 4, 'pool_available': 0, 'requests_waiting': 0}
Traceback (most recent call last):
  File "test_pool.py", line 9, in <module>
    p.wait(timeout=2)
  File "/home/piro/dev/psycopg3/psycopg_pool/psycopg_pool/pool.py", line 93, in wait
    raise PoolTimeout(f"pool initialization incomplete after {timeout} sec")
psycopg_pool.PoolTimeout: pool initialization incomplete after 2 sec
```

</details>

Sometimes it manages to complete a few connections:

<details>

```
DEBUG:psycopg.pool:task created in MainThread: <AddConnection 'pool-1' at 0x7f9f89adeee0>
DEBUG:psycopg.pool:task created in MainThread: <AddConnection 'pool-1' at 0x7f9f89ae43a0>
DEBUG:psycopg.pool:task created in MainThread: <AddConnection 'pool-1' at 0x7f9f89ae4400>
DEBUG:psycopg.pool:task created in MainThread: <AddConnection 'pool-1' at 0x7f9f89ae4460>
DEBUG:psycopg.pool:task created in MainThread: <ShrinkPool 'pool-1' at 0x7f9f89ae42e0>
INFO:psycopg.pool:waiting for pool 'pool-1' initialization
DEBUG:psycopg.pool:task running in pool-1-worker-1: <AddConnection 'pool-1' at 0x7f9f89ae43a0>
DEBUG:psycopg.pool:task running in pool-1-worker-0: <AddConnection 'pool-1' at 0x7f9f89ae4400>
DEBUG:psycopg.pool:task running in pool-1-worker-2: <AddConnection 'pool-1' at 0x7f9f89ae4460>
INFO:psycopg.pool:adding new connection to the pool
INFO:psycopg.pool:adding new connection to the pool
INFO:psycopg.pool:adding new connection to the pool
DEBUG:psycopg.pool:pool 'pool-1' closed
DEBUG:psycopg.pool:task created in MainThread: <StopWorker 'pool-1' at 0x7f9f89ae45e0>
DEBUG:psycopg.pool:task created in MainThread: <StopWorker 'pool-1' at 0x7f9f89ae4ac0>
DEBUG:psycopg.pool:terminating working thread pool-1-worker-2
DEBUG:psycopg.pool:task created in MainThread: <StopWorker 'pool-1' at 0x7f9f89ae4b50>
DEBUG:psycopg.pool:terminating working thread pool-1-worker-1
DEBUG:psycopg.pool:terminating working thread pool-1-worker-0
{'connections_num': 3, 'connections_ms': 9, 'pool_min': 4, 'pool_max': 4, 'pool_size': 4, 'pool_available': 0, 'requests_waiting': 0}
Traceback (most recent call last):
  File "test_pool.py", line 9, in <module>
    p.wait(timeout=2)
  File "/home/piro/dev/psycopg3/psycopg_pool/psycopg_pool/pool.py", line 93, in wait
    raise PoolTimeout(f"pool initialization incomplete after {timeout} sec")
psycopg_pool.PoolTimeout: pool initialization incomplete after 2 sec
```

</details>

The culprit seems the debug line in `MaintenanceTask.__init__()`:

https://github.com/psycopg/psycopg/blob/88643297dd0766751aa15fdbbd6459a52da13cfa/psycopg_pool/psycopg_pool/pool.py#L738-L744

- Removing that line solves the problem.
- If the line is replaced by a normal `print()` the problem is reproduced too. Printing to stdout or stderr is the same.
- If the line is replaced by a `print("...", end=" ")` the problem _is not reproduced_.
- If python runs unbuffered, the problem is reproduced even with `end=" "`.

Will investigate further, or escalate to BPO. However we will probably release a bugfix version without that debug line.

The `AsyncConnectionPool` is not affected. The async version of the `MaintenanceTask` happens to not have that debug line (it is probably a leftover of early development times); however even adding it it doesn't seem to reproduce the issue.

**Comment by dvarrazzo** [comment]
Ok, sanity restored. The problem is a  race condition introduced in 3.1. Printing or logging in certain place was enough to lose the race.
