### ISSUE TITLE
Warning raised randomly on pipeline exit

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#266]
Hi @dlax 

I have noticed some randomness in the way errors are handled in pipeline mode. Which makes sense, because if the client is sending statements, and the server is sending back errors because of something that happened earlier, the order in which things happen is somewhat random.

However I see sometimes warnings such as `error ignored syncing <psycopg.Pipeline [IDLE] (database=piro) at 0x...>: pipeline aborted` happening in the `sync()` at the end of the pipeline block, which seems strange, because sync is pretty much the only thing you could send to exit the state of pipeline aborted.

The test goes like:
```python
import psycopg
with psycopg.connect(autocommit=True, prepare_threshold=0) as conn:
    with conn.pipeline() as p:
        print("select 1")
        conn.execute("select 1")
        print("select foo")
        conn.execute("select foo")
        print("select bar")
        conn.execute("select bar")
        print("select baz")
        conn.execute("select baz")
        print("select sleep")
        conn.execute("select pg_sleep(0.2)")
```
and I can see an output (although not always) of:
```
select 1
select foo
select bar
select baz
select sleep
error ignored syncing <psycopg.Pipeline [IDLE] (database=piro) at 0x7f9b2550dc40>: pipeline aborted
Traceback (most recent call last):
  File "trace.py", line 301, in <module>
    conn.execute("select pg_sleep(0.2)")
  File "/home/piro/dev/psycopg3/psycopg/psycopg/connection.py", line 828, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column "foo" does not exist
LINE 1: select foo
               ^
```

Other times the error ends up managed in `Pipeline.__exit__()`, which is ok too (I'm adding a fix to shorten the traceback here too). Here, however, removing the `baz` query, there is no warning.

```
select 1
select foo
select bar
select sleep
Traceback (most recent call last):
  File "trace.py", line 301, in <module>
    conn.execute("select pg_sleep(0.2)")
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/connection.py", line 881, in pipeline
    yield pipeline
  File "/home/piro/dev/psycopg3/psycopg/psycopg/_pipeline.py", line 197, in __exit__
    self.sync()
  File "/home/piro/dev/psycopg3/psycopg/psycopg/_pipeline.py", line 183, in sync
    self._conn.wait(self._sync_gen())
  File "/home/piro/dev/psycopg3/psycopg/psycopg/connection.py", line 896, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/waiting.py", line 237, in wait_epoll
    s = gen.send(ready)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/_pipeline.py", line 92, in _sync_gen
    yield from self._communicate_gen()
  File "/home/piro/dev/psycopg3/psycopg/psycopg/_pipeline.py", line 105, in _communicate_gen
    self._process_results(queued, results)
  File "/home/piro/dev/psycopg3/psycopg/psycopg/_pipeline.py", line 149, in _process_results
    raise e.error_from_result(result, encoding=pgconn_encoding(self.pgconn))
psycopg.errors.UndefinedColumn: column "foo" does not exist
LINE 1: select foo
               ^
```

As far as I see it, either is good and I assume we can expect randomness here. I will document that errors might be raised at random places during pipeline processing (and `sync()` can be used to force processing of whatever had happened earlier). However, could you please double check if it's normal/unavoidable to get the warning on sync above?

**Comment by dlax** [comment]
> Here, however, removing the `baz` query, there is no warning.

It's harder to get it, but it happens as far as I can tell:
```
select 1
select foo
select bar
error ignored syncing <psycopg.Pipeline [IDLE] (database=denis) at 0x7f3c9ef74df0>: pipeline aborted
Traceback (most recent call last):
  File "/home/denis/src/psycopg3/issue266.py", line 10, in <module>
    conn.execute("select bar")
  File "/home/denis/src/psycopg3/psycopg/psycopg/connection.py", line 828, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column "foo" does not exist
LINE 1: select foo
               ^
```
(This is with d24a26f4ec2d6c1639834f275034820cfeb5eb86.)

But yes, I think this is a normal consequence of the ["Interleaving Result Processing and Query Dispatch"](https://www.postgresql.org/docs/current/libpq-pipeline-mode.html#LIBPQ-PIPELINE-INTERLEAVE) pattern.
