### ISSUE TITLE
Inconsistent behavior between ctypes & c variant

### ISSUE THREAD

**Issue by apollo13** [psycopg/psycopg#301]
Hi, using the following snippet:
```py
import psycopg

with psycopg.connect("dbname=postgres") as conn:
    print(conn.execute("SELECT %s", [[1, 0, 0, 0.5]]).fetchall())
```

I do get:
```
[([1, 0, 0, 0],)]
```
with the pure python variant (note that 0.5 is converted to 0, which is probably okay if those are all seen as ints to be made homogeneous)

and this with `psycopg[binary]` installed:
```
Traceback (most recent call last):
  File "/home/florian/sources/django.git/tests/test.py", line 4, in <module>
    print(conn.execute("SELECT %s", [[1, 0, 0, 0.5]]).fetchall())
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/connection.py", line 723, in execute
    return cur.execute(query, params, prepare=prepare)
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/cursor.py", line 551, in execute
    self._conn.wait(
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/connection.py", line 776, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/waiting.py", line 240, in wait_epoll
    s = gen.send(ready)
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/cursor.py", line 196, in _execute_gen
    pgq = self._convert_query(query, params)
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/cursor.py", line 379, in _convert_query
    pgq.convert(query, params)
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/_queries.py", line 84, in convert
    self.dump(vars)
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/_queries.py", line 95, in dump
    self.params = self._tx.dump_sequence(params, self._want_formats)
  File "psycopg_binary/_psycopg/transform.pyx", line 293, in psycopg_binary._psycopg.Transformer.dump_sequence
  File "psycopg_binary/_psycopg/transform.pyx", line 341, in psycopg_binary._psycopg.Transformer.dump_sequence
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/types/array.py", line 167, in dump
    dump_list(obj)
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/types/array.py", line 154, in dump_list
    ad = self._dump_item(item)
  File "/home/florian/.local/share/virtualenvs/django/lib/python3.10/site-packages/psycopg/types/array.py", line 173, in _dump_item
    return self.sub_dumper.dump(item)
  File "psycopg_binary/_psycopg/adapt.pyx", line 67, in psycopg_binary._psycopg.CDumper.dump
  File "psycopg_binary/types/numeric.pyx", line 55, in psycopg_binary._psycopg._NumberDumper.cdump
  File "psycopg_binary/types/numeric.pyx", line 629, in psycopg_binary._psycopg.dump_int_to_text
TypeError: 'float' object cannot be interpreted as an integer
```

Now I cannot say which behavior I like more (I can understand both to some extend) but it might make sense for the two to behave the same.

**Comment by dvarrazzo** [comment]
Sure, it makes sense and they should behave consistently. Actually, in Psycopg 3.0.13, there was some change around this code, in order to fix #293. Are you playing with this version or with a previous one?

I think that the right behaviour is to not lose precision. PostgreSQL arrays are uniform types: the list `[1, 1.2]` should be dumped as an array of floats or numeric. I'm not sure if I'd like to scan the whole list and, if a float or a Decimal is found, to upgrade the array to a `float[]` or a `numeric[]`. What if there is a float **and** a Decimal in the list?

I think the safest thing to do is to throw an exception. A `DataError` would be better than a `TypeError`.

**Comment by apollo13** [comment]
Yes I am on 3.0.13; I even made sure to check the commits since then but didn't see anything standing out.

> I'm not sure if I'd like to scan the whole list

Me neither in theory it sounds nice but there will be dragons…

> I think the safest thing to do is to throw an exception.

Thinking more about it, I agree. Data truncation is imo unacceptable and scanning the list might start to perform badly at some point.

**Comment by apollo13** [comment]
And one more working test in the Django Testsuite https://github.com/django/django/pull/15687/commits/c9e079b2d5c5dbebc5e59644825055f83fae421c :)

**Comment by dvarrazzo** [comment]
@apollo13 This fix was released in Psycopg 3.0.14.

Please note that this affects most mixed-types array, which now probably raise an exception. It would be worth to check with this version to verify if there aren't any regressions.

Also please note that we are close to release Psycopg 3.1, which will provide a [client-side binding cursor](https://www.psycopg.org/psycopg3/docs/advanced/cursors.html#client-side-binding-cursors). This cursor is less efficient than the normal one, but behaves more similarly to psycopg2 and could be useful where Django generates Data Definition Language statements, which usually [fail using server-side binding](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#server-side-binding).

**Comment by apollo13** [comment]
Ok, will do. As for the client side cursor, not sure… What do you recommend? We (you) already used the sql module to prepare the statement client side…

**Comment by dvarrazzo** [comment]
We can leave the usage of the sql module, Probably the client-binding cursor is more useful to apps doing a lot of DDL and not caring about query planning overhead. Django uses connection for a mix of DDL (rarely) and mostly for query and DML so switching cursor type for different tasks might be more an overhead than something useful.
