### ISSUE TITLE
Broken pgcli dependency on psycopg

### ISSUE THREAD

**Issue by j-bennet** [psycopg/psycopg#368]
Hi @dvarrazzo ,

I initially commented in https://github.com/psycopg/psycopg/issues/257, but decided it's better to open a separate issue.

Recently, I started getting an error running pgcli. Pgcli specifies dependency to `psycopg >= 3.14.0`:

https://github.com/dbcli/pgcli/blob/f858c4d569d6e364a8145def03bac023d03a8204/setup.py#L15

I thought this is because I created a new python 3.10 venv, but it also happens with python 3.9 venv:

```
> pgcli -U postgres
Traceback (most recent call last):
  File "/Users/irinatruong/.pyenv/versions/pgcli39/bin/pgcli", line 5, in <module>
    from pgcli.main import cli
  File "/Users/irinatruong/src/pgcli/pgcli/main.py", line 2, in <module>
    from pgspecial.namedqueries import NamedQueries
  File "/Users/irinatruong/.pyenv/versions/3.9.12/envs/pgcli39/lib/python3.9/site-packages/pgspecial/__init__.py", line 13, in <module>
    from . import iocommands
  File "/Users/irinatruong/.pyenv/versions/3.9.12/envs/pgcli39/lib/python3.9/site-packages/pgspecial/iocommands.py", line 9, in <module>
    import psycopg
  File "/Users/irinatruong/.pyenv/versions/3.9.12/envs/pgcli39/lib/python3.9/site-packages/psycopg/__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
  File "/Users/irinatruong/.pyenv/versions/3.9.12/envs/pgcli39/lib/python3.9/site-packages/psycopg/pq/__init__.py", line 114, in <module>
    import_from_libpq()
  File "/Users/irinatruong/.pyenv/versions/3.9.12/envs/pgcli39/lib/python3.9/site-packages/psycopg/pq/__init__.py", line 106, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found
```

The error goes away when installing `psycopg[binary,pool]`, but in pgcli we depend on `psycopg`, and I had an impression that this is the best practice.

Are we doing this wrong? Should we be depending on `psycopg-binary`?

I'm using a Macbook Pro with macOS Monterey. Is this related to https://github.com/psycopg/psycopg/issues/364?

Please advise.

**Comment by dvarrazzo** [comment]
Yes, this is related to #364.

Using the binary package as a dependency is not a good idea. Apple M1 hardware, for instance, is not supported yet.

The discussion at https://github.com/orgs/Homebrew/discussions/3595 proposes some workaround. I hope they are temporary, but for the moment you can use them.

The ball is in their field. If there are othe repackage managers more reliable please let us know.

**Comment by j-bennet** [comment]
Thanks @dvarrazzo , I'll follow https://github.com/orgs/Homebrew/discussions/3595.

**Comment by dss010101** [comment]
this seems to indicate the issue is Windows.  Im running python3.1 docker image (debian bookworm)  with Docker Desktop and seeing this.  i installed libpq-dev as part of the container build, yet still seeing this.  
Any ideas?
