### ISSUE TITLE
transaction() broken with implicit pipeline transaction

### ISSUE THREAD

**Issue by dlax** [psycopg/psycopg#374]
When a pipeline is entered and does not start with an explicit transaction (i.e. a `BEGIN` statement), the server opens an "implicit transaction". But this transaction cannot hold a `SAVEPOINT`. So on our side, after this implicit transaction got started, the connection is in `IDLE` state, so that when entering a `transaction()` block, we try to insert a `SAVEPOINT` and get:
```python
>>> conn = psycopg.connect(autocommit=True)
>>> with conn.pipeline():
...   conn.execute("select 'implicit'")
...   with conn.transaction():
...     conn.execute("select 'tx'")
...   conn.execute("select 'after'")
... 
<psycopg.Cursor [no result] [ACTIVE, pipeline=ON] (database=denis) at 0x7f7203a3ee80>
error ignored terminating <psycopg.Pipeline [IDLE, pipeline=ON] (database=denis) at 0x7f72038bbfa0>: ROLLBACK TO SAVEPOINT can only be used in transaction blocks
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/denis/src/psycopg3/psycopg/psycopg/connection.py", line 905, in transaction
    with self.pipeline(), tx, self.pipeline():
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/denis/src/psycopg3/psycopg/psycopg/connection.py", line 938, in pipeline
    with pipeline:
  File "/home/denis/src/psycopg3/psycopg/psycopg/_pipeline.py", line 210, in __enter__
    self._conn.wait(self._enter_gen())
  File "/home/denis/src/psycopg3/psycopg/psycopg/connection.py", line 954, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/home/denis/src/psycopg3/psycopg/psycopg/waiting.py", line 240, in wait_epoll
    s = gen.send(ready)
  File "/home/denis/src/psycopg3/psycopg/psycopg/_pipeline.py", line 96, in _enter_gen
    yield from self._sync_gen()
  File "/home/denis/src/psycopg3/psycopg/psycopg/_pipeline.py", line 107, in _sync_gen
    yield from self._fetch_gen(flush=False)
  File "/home/denis/src/psycopg3/psycopg/psycopg/_pipeline.py", line 156, in _fetch_gen
    self._process_results(queued, results)
  File "/home/denis/src/psycopg3/psycopg/psycopg/_pipeline.py", line 171, in _process_results
    raise e.error_from_result(result, encoding=pgconn_encoding(self.pgconn))
psycopg.errors.NoActiveSqlTransaction: SAVEPOINT can only be used in transaction blocks
```

I'll investigate and hopefully get a fix.

**Comment by dvarrazzo** [comment]
Shouldn't `transaction()` issue a BEGIN rather than a SAVEPOINT, if the connection is in IDLE state?

**Comment by dlax** [comment]
The connection is in `ACTIVE` state after the first `SELECT` statement in my example above, so `transaction()` detects this as an "outer transaction" and it pushes a `SAVEPOINT`; but it seems incorrect in this case (since no `BEGIN` got emitted, at least, on client side).

**Comment by dlax** [comment]
https://www.postgresql.org/docs/14/libpq-status.html#LIBPQ-PQTRANSACTIONSTATUS:
> PQTRANS_ACTIVE is reported only when a query has been sent to the server and not yet completed.

That's the case of the first select (sent but not completed yet). If we `.fetchone()` the cursor, the transaction goes back to `IDLE`.
