### ISSUE TITLE
Pool check not inserting new connections

### ISSUE THREAD

**Issue by NBPub** [psycopg/psycopg#395]
I am trying to use a connection pool with a Flask application served by Gunicorn. It seems that overtime, the pool discards bad connections with `pool.check()`, but it does not replenish itself. I have been able to add connections manually, `pool._add_connection(None)`. 

I am not sure if this is related to #370. I have been reading through the docs and #247, which leads me to believe that my pool may be misbehaving. Apologies if this post has unrelated information Thank you for any attention and help in my understanding of the `ConnectionPool`.

## Design
````
# db_pool.py, creates single instance as global
from psycopg_pool import ConnectionPool
conninfo = ""
pool = ConnectionPool(conninfo,timeout=15,min_size=4,max_size=10, open=False)

# on successful database connection, another module opens the pool with app startup
from .db_pool import pool
pool.open()

# other modules import and use the pool
with pool.connection() as conn:
    cur = conn.cursor() 
    # do stuff
return page    
````
*I get same behavior with default pool parameters. Given the global state of the pool, I cannot delete and recreate it on error.*

## Errors
I've been trying to troubleshoot this and am checking pool stats and running a `pool.check()` before each app request. When available connections are low, I've tried multiple checks. Despite this, the pool dwindles to 0 available connections over time. It seems that bad connections are discarded, but not replaced.

`discarding broken connection: <psycopg.Connection [BAD] at 0x7f8bb153f0>`

After some time, the pool times out. I'm assuming this is due to 0 available connections. It looks like the pool tried to grow, but did not insert a new connection.
```
discarding broken connection: <psycopg.Connection [BAD] at 0x7f8b297eb0>
[2022-09-28 09:12:38 -0700] [14] [ERROR] Exception on /home/page/ [POST]
.
.
.
    raise self.error
psycopg_pool.PoolTimeout: couldn't get a connection after 15 sec

[2022-09-28 09:12:38 -0700] [14] [INFO] # stats printout to logs
{'requests_num': 1, 'requests_queued': 1, 'requests_errors': 1, 
'requests_wait_ms': 15000, 'pool_min': 4, 'pool_max': 10, 
'pool_size': 5, 'pool_available': 0, 'requests_waiting': 1} 
```

<details><summary>Logs with pool.get_stats()</summary>
<pre><code>
# startup
[2022-09-27 12:53:28 -0700] [12] [INFO] Booting worker with pid: 12
[2022-09-27 12:53:28 -0700] [13] [INFO] Booting worker with pid: 13
# first few requests
[2022-09-27 12:54:44 -0700] [13] [INFO] {'connections_num': 4, 'connections_ms': 562, 'pool_min': 4, 'pool_max': 10, 'pool_size': 4, 'pool_available': 4, 'requests_waiting': 0}
[2022-09-27 13:01:00 -0700] [12] [INFO] {'connections_num': 4, 'connections_ms': 276, 'pool_min': 4, 'pool_max': 10, 'pool_size': 4, 'pool_available': 2, 'requests_waiting': 0}
[2022-09-27 13:01:22 -0700] [12] [INFO] {'connections_num': 4, 'connections_ms': 276, 'requests_num': 2, 'usage_ms': 163, 'pool_min': 4, 'pool_max': 10, 'pool_size': 4, 'pool_available': 2, 'requests_waiting': 0}
[2022-09-27 13:01:42 -0700] [13] [INFO] {'connections_num': 4, 'connections_ms': 562, 'requests_num': 3, 'usage_ms': 96, 'pool_min': 4, 'pool_max': 10, 'pool_size': 4, 'pool_available': 4, 'requests_waiting': 0}
[2022-09-27 13:01:43 -0700] [13] [INFO] {'connections_num': 4, 'connections_ms': 562, 'requests_num': 4, 'usage_ms': 162, 'pool_min': 4, 'pool_max': 10, 'pool_size': 4, 'pool_available': 4, 'requests_waiting': 0}
# not much later
[2022-09-27 14:01:41 -0700] [12] [INFO] {'connections_num': 4, 'connections_ms': 276, 'requests_num': 6, 'usage_ms': 394, 'pool_min': 4, 'pool_max': 10, 'pool_size': 4, 'pool_available': 2, 'requests_waiting': 0}
[2022-09-27 14:02:30 -0700] [12] [INFO] {'connections_num': 4, 'connections_ms': 276, 'requests_num': 7, 'usage_ms': 451, 'pool_min': 4, 'pool_max': 10, 'pool_size': 4, 'pool_available': 1, 'requests_waiting': 0}
[2022-09-27 14:02:48 -0700] [12] [INFO] {'connections_num': 4, 'connections_ms': 276, 'requests_num': 8, 'usage_ms': 530, 'pool_min': 4, 'pool_max': 10, 'pool_size': 4, 'pool_available': 0, 'requests_waiting': 0}
# Error 
# - PoolTimeout
[2022-09-27 14:03:03 -0700] [12] [INFO] {'connections_num': 4, 'connections_ms': 276, 'requests_num': 9, 'usage_ms': 530, 'requests_queued': 1, 'requests_errors': 1, 'requests_wait_ms': 15000, 'pool_min': 4, 'pool_max': 10, 'pool_size': 5, 'pool_available': 0, 'requests_waiting': 1}
</code></pre>
</details>

## Workaround
If I catch the resulting error page and try to insert a new connection, the next request does not timeout. However without the code below, even with a plethora of pool checks, connections will not be added to the pool and all resulting requests will timeout.

```
if pool.get_stats()['pool_available'] == 0:
    pool._add_connection(None)
```

I may have a poorly designed application or understanding of how the connection pool is supposed to work. As it stands, I could simply check the stats with each request and insert connections as necessary. 

I am also considering trying a `NullConnectionPool`. If that runs smoothly, would it indicate that my problem is with the `ConnectionPool` itself? 

## Gunicorn???
I don't understand Gunicorn well, so am not sure if it's a problem with its workers. I may try the Flask default WSGI, Werkzeug, to see if there is an effect. Very rarely I've seen the Gunicorn workers timeout, exit, and get replaced. This didn't help the state of the pool. I am not sure if they have the pool defined when booting.
```
[2022-09-26 20:45:18 -0700] [1] [CRITICAL] WORKER TIMEOUT (pid:13)
error ignored in rollback on <psycopg.Connection [ACTIVE] (host=host database=database) at 0x7f911c08b0>: sending query and params failed: another command is already in progress
closing returned connection: <psycopg.Connection [ACTIVE] (host=host database=database) at 0x7f911c08b0>
discarding closed connection: <psycopg.Connection [BAD] at 0x7f911c08b0>
[2022-09-26 20:45:18 -0700] [13] [INFO] Worker exiting (pid: 13)
[2022-09-26 20:45:18 -0700] [15] [INFO] Booting worker with pid: 15
discarding closed connection: <psycopg.Connection [BAD] at 0x7f911c08b0>

# error
psycopg.OperationalError: the connection is lost
```

**Comment by dvarrazzo** [comment]
Hello,

You can use:

```python
import logging

logging.basicConfig(
    level=logging.INFO,
   format='%(asctime)s %(levelname)s %(message)s')
   
logging.getLogger("psycopg.pool").setLevel(logging.INFO)
```

(or something similar, if it integrates with your logging system) in order to enable pool logging, and you can take a look at the logs to figure out what's going on.

Note that if your program forks (gunicorn workers) the pool must be created after the fork, you cannot share a pool across processes.

**Comment by nishantbb** [comment]
Thank you, I will enable the pool logging to figure out more.

On the forking note, I was wary of the repetitive logs and figured I should establish the pool prior to the fork. Does each gunicorn worker create and use their own pool, if it's created after the fork?

**Comment by NBPub** [comment]
Thanks. I have implemented pool logging and think I can see what you're saying about the fork. If I create the pool before the fork worker [1], then access the pool from other workers [x,y,z]. Then I request, use, and return connections to the pool with [x,y,z], but they probably cannot add connections without an explicit `pool._add_connection`?

If I create the pool after the fork, then will each worker [x,y,z] be using their own pool? 

I think I'll be able to close this today, just need some time to play with the forks.

**Comment by dvarrazzo** [comment]
Yes, every fork will use its own pool. Mind that this would probably exhaust the server available connections very quickly.

For a forking server, I think it would be wiser to use an external connection pool such as pgbouncer and maybe leave the option to use a pool in your application, but leave it as a configuration option, and use a NullPool if an in-process pool is not needed.

I don't think `pool._add_connection` is needed: it's not supposed to be used publicly. Would you mind sharing some of your logs showing what happens in a pool after a fork?

I think it would be nice to add a check so that the pool would notice immediately that there was a fork. I think it can recover from that by running `check()`, which should detect that the connections are no more in usable state.

**Comment by NBPub** [comment]
Thank you for the advice, I think a NullPool might be the most convenient route forward for me now.

As mentioned, I've been running `check()` before every request. So as soon as the site is accessed, the pool should detect the fork.  I've been wanting Gunicorn to "preload" the application as the forked workers seem to be repeating scheduled tasks. If I get around that, then there'd be no reason to have the fork be right at the beginning, before application startup.

<details><summary>Logs for a fresh start, it seems that worker [1] is populating the pool before the fork.</summary>

```python
[2022-09-30 09:46:16 -0700] [1] [INFO] Attempting database connection
[2022-09-30 09:46:16 -0700] [1] [CRITICAL] Database connection failed: connection failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
[2022-09-30 09:46:16 -0700] [1] [INFO] trying again, 1/3 attempts . . .
[2022-09-30 09:46:19 -0700] [1] [INFO] Attempting database connection
[2022-09-30 09:46:20 -0700] [1] [INFO] Database connection established.
[2022-09-30 09:46:20 -0700] [1] [INFO] Database ready.
[2022-09-30 09:46:20 -0700] [1] [INFO] Scheduler disabled.
[2022-09-30 09:46:20 -0700] [1] [INFO] . . . starting BeatLog . . .
[2022-09-30 09:46:20 -0700] [1] [INFO] adding new connection to the pool
[2022-09-30 09:46:20 -0700] [1] [INFO] adding new connection to the pool
[2022-09-30 09:46:20 -0700] [1] [INFO] adding new connection to the pool
[2022-09-30 09:46:20 -0700] [1] [INFO] adding new connection to the pool
[2022-09-30 09:46:21 -0700] [1] [INFO] Starting gunicorn 20.1.0
[2022-09-30 09:46:21 -0700] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2022-09-30 09:46:21 -0700] [1] [INFO] Using worker: sync
[2022-09-30 09:46:21 -0700] [11] [INFO] Booting worker with pid: 11
[2022-09-30 09:46:21 -0700] [12] [INFO] Booting worker with pid: 12
[2022-09-30 09:46:21 -0700] [13] [INFO] Booting worker with pid: 13
[2022-09-30 09:46:33 -0700] [11] [INFO] connection requested from 'pool-1'
[2022-09-30 09:46:33 -0700] [11] [INFO] connection given by 'pool-1'
[2022-09-30 09:46:34 -0700] [11] [INFO] returning connection to 'pool-1'
```
</details>

<details><summary>Logs showing long term, connections dropping. I assume [1] makes the pool again.</summary>

```python
[2022-09-29 17:01:34 -0700] [1] [INFO] Attempting database connection
[2022-09-29 17:01:34 -0700] [1] [INFO] Database connection established.
[2022-09-29 17:01:35 -0700] [1] [INFO] Database ready.
[2022-09-29 17:01:35 -0700] [1] [INFO] Scheduler initialized.
[2022-09-29 17:01:36 -0700] [1] [INFO] Scheduled tasks enabled:
[2022-09-29 17:01:36 -0700] [1] [INFO]  home IP check every 1 hours, starting in 30s
[2022-09-29 17:01:36 -0700] [1] [INFO]  log check every 1 hours, starting in 15 min
[2022-09-29 17:01:36 -0700] [1] [INFO] . . . starting BeatLog . . .
[2022-09-29 17:01:36 -0700] [1] [INFO] Starting gunicorn 20.1.0
[2022-09-29 17:01:36 -0700] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2022-09-29 17:01:36 -0700] [1] [INFO] Using worker: sync
[2022-09-29 17:01:36 -0700] [11] [INFO] Booting worker with pid: 11
[2022-09-29 17:01:36 -0700] [12] [INFO] Booting worker with pid: 12
[2022-09-29 17:01:36 -0700] [13] [INFO] Booting worker with pid: 13
[2022-09-29 17:01:49 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-29 17:01:49 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-29 17:01:49 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-29 17:01:54 -0700] [11] [INFO] connection requested from 'pool-1'
[2022-09-29 17:01:54 -0700] [11] [INFO] connection given by 'pool-1'
[2022-09-29 17:01:55 -0700] [11] [INFO] returning connection to 'pool-1'
.
.
.
[2022-09-29 18:02:05 -0700] [1] [INFO] Scheduled Home IP check complete
[2022-09-29 18:16:36 -0700] [1] [INFO] Scheduled Log check complete 
[2022-09-29 21:58:27 -0700] [13] [INFO] connection requested from 'pool-1'
[2022-09-29 21:58:27 -0700] [13] [INFO] connection given by 'pool-1'
[2022-09-29 21:58:28 -0700] [13] [INFO] returning connection to 'pool-1'

# pool check discards broken connection?
[2022-09-29 21:58:28 -0700] [13] [INFO] discarding expired connection # 1
[2022-09-29 21:58:28 -0700] [12] [WARNING] discarding broken connection: <psycopg.Connection [BAD] at 0x7f9c0e0430>
[2022-09-29 21:58:33 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-29 21:58:33 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-29 21:58:33 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-29 21:58:33 -0700] [12] [INFO] discarding expired connection # 2
[2022-09-29 21:58:33 -0700] [11] [WARNING] discarding broken connection: <psycopg.Connection [BAD] at 0x7f9c0bfc70> # 1
[2022-09-29 21:58:33 -0700] [11] [WARNING] discarding broken connection: <psycopg.Connection [BAD] at 0x7f9c0e0430> # 2
[2022-09-29 21:58:37 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-29 21:58:37 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-29 21:58:37 -0700] [12] [INFO] looking up locations . . .
[2022-09-29 21:58:38 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-29 21:58:38 -0700] [12] [INFO] discarding expired connection # 3
[2022-09-29 21:59:17 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-29 21:59:17 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-29 21:59:17 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-29 21:59:17 -0700] [12] [INFO] discarding expired connection # 4

# no available connection, grows without adding connection, pool timeout
[2022-09-29 21:59:34 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-29 21:59:34 -0700] [12] [INFO] growing pool 'pool-1' to 5
[2022-09-29 21:59:49 -0700] [12] [ERROR] Exception on /Logs/add [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/beatlog/logs.py", line 53, in add_log_file
    with pool.connection() as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/psycopg_pool/pool.py", line 114, in connection
    conn = self.getconn(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/psycopg_pool/pool.py", line 158, in getconn
    conn = pos.wait(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/psycopg_pool/pool.py", line 714, in wait
    raise self.error
psycopg_pool.PoolTimeout: couldn't get a connection after 15 sec

# stats of pool during error
[2022-09-29 21:59:49 -0700] [12] [INFO] pool status on error:
{'connections_num': 4, 'connections_ms': 318, 'requests_num': 17, 'usage_ms': 3658, 'connections_lost': 1, 'requests_queued': 1, 'requests_errors': 1, 'requests_wait_ms': 15000, 'pool_min': 4, 'pool_max': 10, 'pool_size': 5, 'pool_available': 0, 'requests_waiting': 1}
[2022-09-29 21:59:49 -0700] [12] [INFO] adding new connection to the pool
[2022-09-29 21:59:49 -0700] [12] [INFO] adding new connection to the pool
[2022-09-29 21:59:49 -0700] [12] [INFO] adding new connection to the pool
[2022-09-29 21:59:49 -0700] [12] [INFO] adding new connection to the pool

# stats after 4 connections added
[2022-09-29 21:59:49 -0700] [12] [INFO] pool status fix:
{'connections_num': 8, 'connections_ms': 421, 'requests_num': 17, 'usage_ms': 3658, 'connections_lost': 1, 'requests_queued': 1, 'requests_errors': 1, 'requests_wait_ms': 15000, 'pool_min': 4, 'pool_max': 10, 'pool_size': 5, 'pool_available': 4, 'requests_waiting': 0}

# other workers discarding bad connections
[2022-09-29 21:59:49 -0700] [13] [WARNING] discarding broken connection: <psycopg.Connection [BAD] at 0x7f9c0e05b0>
[2022-09-29 21:59:49 -0700] [13] [WARNING] discarding broken connection: <psycopg.Connection [BAD] at 0x7f9c0e0520>
[2022-09-29 21:59:49 -0700] [13] [WARNING] discarding broken connection: <psycopg.Connection [BAD] at 0x7f9c0bfc70>
[2022-09-29 22:00:01 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-29 22:00:01 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-29 22:00:01 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-29 22:00:01 -0700] [11] [WARNING] discarding broken connection: <psycopg.Connection [BAD] at 0x7f9c0e0520>
[2022-09-29 22:00:01 -0700] [11] [WARNING] discarding broken connection: <psycopg.Connection [BAD] at 0x7f9c0e05b0>
[2022-09-29 22:00:08 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-29 22:00:08 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-29 22:00:08 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-29 22:00:09 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-29 22:00:09 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-29 22:00:09 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-29 22:02:05 -0700] [1] [INFO] Scheduled Home IP check complete
[2022-09-29 22:16:36 -0700] [1] [INFO] Scheduled Log check complete 
.
.
.
[2022-09-30 09:02:05 -0700] [1] [INFO] Scheduled Home IP check complete
[2022-09-30 09:16:37 -0700] [1] [INFO] Scheduled Log check complete 
[2022-09-30 09:27:03 -0700] [11] [INFO] connection requested from 'pool-1' # timeout again
[2022-09-30 09:27:03 -0700] [11] [INFO] growing pool 'pool-1' to 5
[2022-09-30 09:27:18 -0700] [11] [ERROR] Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/beatlog/home.py", line 26, in home
    with pool.connection() as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/psycopg_pool/pool.py", line 114, in connection
    conn = self.getconn(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/psycopg_pool/pool.py", line 158, in getconn
    conn = pos.wait(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/psycopg_pool/pool.py", line 714, in wait
    raise self.error
psycopg_pool.PoolTimeout: couldn't get a connection after 15 sec

[2022-09-30 09:27:19 -0700] [11] [INFO] pool status on error:
{'connections_num': 4, 'connections_ms': 318, 'requests_num': 8, 'usage_ms': 1909, 'connections_lost': 4, 'requests_queued': 1, 'requests_errors': 1, 'requests_wait_ms': 15000, 'pool_min': 4, 'pool_max': 10, 'pool_size': 5, 'pool_available': 0, 'requests_waiting': 1}
[2022-09-30 09:27:19 -0700] [11] [INFO] adding new connection to the pool
[2022-09-30 09:27:19 -0700] [11] [INFO] adding new connection to the pool
[2022-09-30 09:27:19 -0700] [11] [INFO] adding new connection to the pool
[2022-09-30 09:27:19 -0700] [11] [INFO] adding new connection to the pool
[2022-09-30 09:27:19 -0700] [11] [INFO] pool status fix:
{'connections_num': 8, 'connections_ms': 424, 'requests_num': 8, 'usage_ms': 1909, 'connections_lost': 4, 'requests_queued': 1, 'requests_errors': 1, 'requests_wait_ms': 15000, 'pool_min': 4, 'pool_max': 10, 'pool_size': 5, 'pool_available': 4, 'requests_waiting': 0}

[2022-09-30 09:27:43 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-30 09:27:43 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-30 09:27:43 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-30 09:27:43 -0700] [12] [INFO] discarding expired connection # 1
[2022-09-30 09:27:51 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-30 09:27:51 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-30 09:27:51 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-30 09:27:51 -0700] [12] [INFO] discarding expired connection # 2
[2022-09-30 09:27:57 -0700] [11] [INFO] connection requested from 'pool-1'
[2022-09-30 09:27:57 -0700] [11] [INFO] connection given by 'pool-1'
[2022-09-30 09:27:57 -0700] [11] [INFO] returning connection to 'pool-1'
[2022-09-30 09:28:03 -0700] [11] [INFO] connection requested from 'pool-1'
[2022-09-30 09:28:03 -0700] [11] [INFO] connection given by 'pool-1'
[2022-09-30 09:28:03 -0700] [11] [INFO] returning connection to 'pool-1'
[2022-09-30 09:28:09 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-30 09:28:09 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-30 09:28:09 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-30 09:28:09 -0700] [12] [INFO] discarding expired connection # 3
[2022-09-30 09:28:14 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-30 09:28:14 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-30 09:28:15 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-30 09:28:15 -0700] [12] [INFO] discarding expired connection # 4
[2022-09-30 09:28:21 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-30 09:28:36 -0700] [12] [ERROR] Exception on /geo/assess/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/beatlog/geography.py", line 71, in geography_assess
    with pool.connection() as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/psycopg_pool/pool.py", line 114, in connection
    conn = self.getconn(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/psycopg_pool/pool.py", line 158, in getconn
    conn = pos.wait(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/psycopg_pool/pool.py", line 714, in wait
    raise self.error
psycopg_pool.PoolTimeout: couldn't get a connection after 15 sec

[2022-09-30 09:28:36 -0700] [12] [INFO] pool status on error:
{'connections_num': 8, 'connections_ms': 421, 'requests_num': 25, 'usage_ms': 3994, 'connections_lost': 1, 'requests_queued': 2, 'requests_errors': 2, 'requests_wait_ms': 30000, 'pool_min': 4, 'pool_max': 10, 'pool_size': 5, 'pool_available': 0, 'requests_waiting': 1}
[2022-09-30 09:28:36 -0700] [12] [INFO] adding new connection to the pool
[2022-09-30 09:28:36 -0700] [12] [INFO] adding new connection to the pool
[2022-09-30 09:28:36 -0700] [12] [INFO] adding new connection to the pool
[2022-09-30 09:28:36 -0700] [12] [INFO] adding new connection to the pool
[2022-09-30 09:28:36 -0700] [12] [INFO] pool status fix:
{'connections_num': 12, 'connections_ms': 669, 'requests_num': 25, 'usage_ms': 3994, 'connections_lost': 1, 'requests_queued': 2, 'requests_errors': 2, 'requests_wait_ms': 30000, 'pool_min': 4, 'pool_max': 10, 'pool_size': 5, 'pool_available': 4, 'requests_waiting': 0}

[2022-09-30 09:28:46 -0700] [12] [INFO] connection requested from 'pool-1'
[2022-09-30 09:28:46 -0700] [12] [INFO] connection given by 'pool-1'
[2022-09-30 09:28:46 -0700] [12] [INFO] returning connection to 'pool-1'
[2022-09-30 09:30:22 -0700] [11] [INFO] connection requested from 'pool-1'
[2022-09-30 09:30:22 -0700] [11] [INFO] connection given by 'pool-1'
[2022-09-30 09:30:22 -0700] [11] [INFO] returning connection to 'pool-1'
.
.
.
```
</details>

**Comment by NBPub** [comment]
As a final test, I am running the application in two containers:

1. Null connection pool - theoretically the same as requesting a new connection with each page
2. Connection pool + `checks()` + `._add_connections()` - I know this is not desired behavior. I just want to see if/how it fails. 
Previously (logs above) I let the connections expire and then tried a few `.add_connections()` when an error was caught.


I think my problem is in the design of the application, and I may be limited by importing the pool as a global with Flask blueprints. Due to this, I can't "wait" until the fork, I believe. I'm planning to commit recent changes [here](https://github.com/NBPub/BeatLog) soon, but it's currently outdated.

If I figure out more on the scheduled tasks ([APScheduler](https://github.com/agronholm/apscheduler) <> [FlaskAPScheduler](https://github.com/viniciuschiele/flask-apscheduler)), and how to work around those with Gunicorn workers, then I'll be able to try again without "preloading" the flask application. 

I'll check back in if I get there. Thanks for your help.

**Comment by dvarrazzo** [comment]
If you can detect the moment when the fork happens, you might start a pool with `open=False` and then call `pool.open()` after the fork.

I'm closing this here: it was a good exploration but I don't think there's anything actionable for us. I'll make some tests and see if we can do something to make behaviours more predictable in case of fork. Input is welxome.

Cheers 👋

**Comment by NBPub** [comment]
Thank you, I had meant to close with the last comment. The `ConnectionPool` is behaving properly, I need to use Gunicorn's server hooks to see if I can load things in the appropriate order.

I will try waiting to open the pool until that first request, and then check it to see if that gives the desired behavior (forked worker can discard and replace connections on its own). I can post the final result for my own edification. Editing my previous comment to add the pool logs.

Cheers!
