### ISSUE TITLE
cursor.fetchall() treat the data as text format when enable binary format result 

### ISSUE THREAD

**Issue by ZENOTME** [psycopg/psycopg#434]
I use Psycopg to test decimal type of our database.

Psycopg version:
psycopg           3.1.4
psycopg-binary    3.1.4

my code:
```
  import psycopg
  from decimal import *;
  conn = psycopg.connect(host="127.0.0.1", port=4566, user="root", dbname="dev")
  cur = conn.cursor(binary=True)
  cur.execute("select 'Inf'::Decimal")
  data = cur.fetchall()
  print(data)
```
I'm sure the database return result as binary format but I got the error:
```
Traceback (most recent call last):
  File "/User/**/Project/pgsql_client/psycopg/test_decimal.py", line 7, in <module>
    data = cur.fetchall()
  File "/Users/**Library/Python/3.9/lib/python/site-packages/psycopg/cursor.py", line 853, in fetchall
    records = self._tx.load_rows(self._pos, self.pgresult.ntuples, self._make_row)
  File "psycopg_binary/_psycopg/transform.pyx", line 467, in psycopg_binary._psycopg.Transformer.load_rows
  File "psycopg_binary/types/numeric.pyx", line 426, in psycopg_binary._psycopg.NumericLoader.cload
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 4: invalid continuation byte
```

And then I let the database return text format and it works! It's weird because I have already enable binary format. 
Why Psycopg treat the return as text format? Do I miss some config?

**Comment by ZENOTME** [comment]
> Which version of Postgres are you using? Is there a moment in which your objects start reporting something different?

I test in [risingwave](https://github.com/risingwavelabs/risingwave). It's a database compatible with Postgres.
I try to reproduce result you give above, something looks different 

```
>>> conn = psycopg.connect(host="127.0.0.1", port=4566, user="root", dbname="dev");
>>> psycopg.pq.__impl__
'binary'  # looks different here 
>>> cur = conn.cursor(binary=True)
>>> cur.execute("select 'Inf'::Decimal")
<psycopg.Cursor [TUPLES_OK] [IDLE] (host=127.0.0.1 port=4566 user=root database=dev) at 0x10661e4c0>
>>> cur.fetchone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/**/Library/Python/3.9/lib/python/site-packages/psycopg/cursor.py", line 817, in fetchone
    record = self._tx.load_row(self._pos, self._make_row)
  File "psycopg_binary/_psycopg/transform.pyx", line 526, in psycopg_binary._psycopg.Transformer.load_row
  File "psycopg_binary/types/numeric.pyx", line 426, in psycopg_binary._psycopg.NumericLoader.cload
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 4: invalid continuation byte
>>> cur.format
<Format.BINARY: 1>
>>> cur.pgresult.get_value(0,0)
b'\x00\x00\x00\x00\xd0\x00\x00\x00'. # At [4] there's also a \xd0, so the database return the correct result
>>> cur.pgresult.fformat(0)
0  # here is weird, the result is reported a text type.
>>> cur.pgresult.ftype(0)
1700
>>> psycopg.postgres.types[1700]
<TypeInfo: numeric (oid: 1700, array oid: 1231)>
>>> cur.adapters.get_loader(1700, 1)
<class 'psycopg_binary._psycopg.NumericBinaryLoader'> # our loader is different?
>>> cur.adapters.get_loader(1700, 0)
<class 'psycopg_binary._psycopg.NumericLoader'>

```

**Comment by dvarrazzo** [comment]
It's a compatibility bug in Risingwave then. The return reports a text result.

We can't guarantee compatibility with PostgreSQL-derived databases. We have done it [for CockroachDB](https://www.psycopg.org/psycopg3/docs/api/crdb.html), but as a partnership that has involved work on both parts to tweak the data models.

In this case, however it's simply a bug on their side: the type reported and the format seem compatible, just the binary indicator is wrong.
