### ISSUE TITLE
 psycopg.connect treats 'localhost' differently than '127.0.0.1' 

### ISSUE THREAD

**Issue by pashagolub** [psycopg/psycopg#454]
Hello, I found a weird behavior trying to use patroni with psycopg3 on Windows. The simplest test case is:
```python
>>> import psycopg
>>> c = psycopg.connect(host='127.0.0.1', user='pasha', dbname='timetable')
>>> c2 = psycopg.connect(host='localhost', user='pasha', dbname='timetable')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pasha\AppData\Roaming\Python\Python311\site-packages\psycopg\connection.py", line 727, in connect
    raise ex.with_traceback(None)
psycopg.OperationalError: connection failed: :1), port 5432 failed: fe_sendauth: no password supplied
```
I'm waiting the same functionality but 'localhost' needs a password even though I have `trust` settings. Another case on another environment produced such output:
```python
>>> import psycopg 
>>> c = psycopg.connect(host='localhost', user='postgres') 
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module> 
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\psycopg\connection.py", line 727, in connect 
    raise ex.with_traceback(None) 
psycopg.OperationalError: connection failed: :1), port 5432 failed: could not receive data from server: Socket is not connected (0x00002749/10057) 
could not send SSL negotiation packet: Socket is not connected (0x00002749/10057) 
>>> c = psycopg.connect(host='127.0.0.1', user='postgres')
```

The same situation but different results. My suspicious is psycopg is trying to resolve 'localhost' as IPv6 thus these strange things.

Best regards

**Comment by dvarrazzo** [comment]
Hello. Yes, I have had similar problems in the past. The problem is usually in your hosts file.

Can you connect to the server using psql? Psycopg wouldn't do anything different.

**Comment by pashagolub** [comment]
Thanks. I checked psql and found similar situation. Seems like `localhost` is really resolves to IPv6. Check this output:

```
nslookup localhost
..
Name:    localhost
Addresses:  ::1
          127.0.0.1
```

Since the first answer is `::1` that might be the problem.
