### ISSUE TITLE
psycopg v3.1.8 breaks alembic & sqlalchemy

### ISSUE THREAD

**Issue by MarceColl** [psycopg/psycopg#487]
Hello!

The latest release 3.1.8 breaks alembic with the following error

```
Traceback (most recent call last):
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mcoll/capchase/code/client-monorepo/apps/metrics-api/alembic/env.py", line 92, in <module>
    run_migrations_online()
  File "/home/mcoll/capchase/code/client-monorepo/apps/metrics-api/alembic/env.py", line 77, in run_migrations_online
    with connectable.connect() as connection:
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3249, in connect
    return self._connection_cls(self)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3273, in raw_connection
    return self.pool.connect()
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1253, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 715, in checkout
    rec = pool._do_get()
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 283, in _do_get
    return self._create_connection()
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 915, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 473, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 487, in __call__
    fn(*args, **kw)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1881, in go
    return once_fn(*arg, **kw)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 746, in first_connect
    dialect.initialize(c)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg.py", line 356, in initialize
    info = self._type_info_fetch(connection, "hstore")
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg.py", line 342, in _type_info_fetch
    return TypeInfo.fetch(connection.connection, name)
  File "/home/mcoll/.cache/pypoetry/virtualenvs/metrics-api-_SqXIYYQ-py3.10/lib/python3.10/site-packages/psycopg/_typeinfo.py", line 86, in fetch
    raise TypeError(
TypeError: expected Connection or AsyncConnection, got _AdhocProxiedConnection
```

It seems like you are now checking the connection type to see what to do with it and if it's not one of your known connection types you throw an error.

It was introduced with this change: https://github.com/psycopg/psycopg/commit/f073e98cb9546c36ea5102a653a7e811a2390d44

**Comment by MarceColl** [comment]
It seems they are aware and consider it their issue, so feel free to close. (at least this may serve as visibility)

https://github.com/sqlalchemy/sqlalchemy/issues/9106

**Comment by zzzeek** [comment]
psycopg is new but hopefully 5 years from now they dont make changes like this ;)

**Comment by dvarrazzo** [comment]
I understand that Mike is fixing the issue their side, so ok, let's close this.

I apologise for this breakage, and propose #488 to catch this type of problems either and coordinate better.

**Comment by MarceColl** [comment]
Thanks for the quick response!
