### ISSUE TITLE
Pool loses connections after cancellation of coroutine

### ISSUE THREAD

**Issue by Tiendil** [psycopg/psycopg#509]
Hi!

First of all, thanks for the good work — psycopg is a great and very helpful library.

I recently encountered a strange behaviour that looks like a bug.

If we wait for a connection in a coroutine and cancel the coroutine, then the pool will lose one of the connections forever.

See the code example below.

Environment:

```
python 3.9
psycopg = 3.1.8
psycopg-pool = 3.1.6
docker: postgres:13.7-alpine
```

Code:

``` python
import asyncio
import pprint

import psycopg_pool


maximum_connections = 3
maximum_timeout = 2.0


async def create_pool():
    return psycopg_pool.AsyncConnectionPool(
        # docker: postgres:13.7-alpine
        'postgresql://default:default@postgres:5432/test?connect_timeout=10',
        min_size=0,
        max_size=maximum_connections,
        timeout=maximum_timeout,
        num_workers=1,  # changing this parameter does not help => set it to 1
        name='test_pool',
        open=False)


async def run_and_cancel(pool):
    '''
    - run more coroutines than maximum connections
    - wait till they get all connections, and others will be in waiting state
    - cancel all coroutins
    '''
    work_markers = set()

    async def fake_operation(x):
        async with pool.connection() as connection:
            async with connection.cursor() as cursor:
                await cursor.execute('SELECT 1')

                await cursor.fetchall()

                work_markers.add(x)

                while True:
                    await asyncio.sleep(0.001)

    # magic number to be sure that some requests for connections will be waiting
    n = maximum_connections * 2 + 1

    tasks = [fake_operation(i) for i in range(n)]
    tasks = [asyncio.ensure_future(t) for t in tasks]

    # wait till maximum_connections will be received from the pool
    # and queries will be made
    while len(work_markers) != maximum_connections:
        await asyncio.sleep(0.001)

    for task in tasks:
        task.cancel()


async def try_to_get_connection(pool):
    'try to get a single connection from the pool'

    async with pool.connection() as connection:
        async with connection.cursor() as cursor:
            await cursor.execute('SELECT 1')
            await cursor.fetchall()


def print_pool_stats(pool):
    print('new pool stats:')
    pprint.pprint(pool.get_stats())


async def main():
    print('create & open pool')

    pool = await create_pool()

    await pool.open(wait=False)

    print_pool_stats(pool)

    print('run a lot of async tasks, part of which will wait for connections')
    print('cancel all of them when all available connections taken')

    await run_and_cancel(pool)

    print_pool_stats(pool)

    # as I understand the logic of the pool:
    #  after all async tasks cancelled
    # pool should return connections to an internal list of free connections
    # even if it should wait for a timeout, timeout x 3 should be enough time to return all connections to the free state
    # Also, increasing waiting time here does not help
    print('Wait the time after which all connections should be available')
    await asyncio.sleep(maximum_timeout * 3)

    print_pool_stats(pool)

    print('here all connections should be available for usage')
    print('=> try to take one connection')

    # Here will be psycopg_pool.PoolTimeout
    await try_to_get_connection(pool)


if __name__ == '__main__':
    asyncio.run(main())
```

Output:

```
create & open pool
new pool stats:
{'pool_available': 0,
 'pool_max': 3,
 'pool_min': 0,
 'pool_size': 0,
 'requests_waiting': 0}
run a lot of async tasks, part of which will wait for connections
cancel all of them when all available connections taken
new pool stats:
{'connections_ms': 11,
 'connections_num': 3,
 'pool_available': 0,
 'pool_max': 3,
 'pool_min': 0,
 'pool_size': 3,
 'requests_num': 7,
 'requests_queued': 7,
 'requests_wait_ms': 30,
 'requests_waiting': 4}
Wait the time after which all connections should be available
new pool stats:
{'connections_ms': 11,
 'connections_num': 3,
 'pool_available': 0,
 'pool_max': 3,
 'pool_min': 0,
 'pool_size': 3,
 'requests_num': 7,
 'requests_queued': 7,
 'requests_wait_ms': 90,
 'requests_waiting': 1,
 'usage_ms': 13}
here all connections should be available for usage
=> try to take one connection
Traceback (most recent call last):
  File "/app/./psycopg_pool_cancel_while_waiting.py", line 106, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/./psycopg_pool_cancel_while_waiting.py", line 102, in main
    await try_to_get_connection(pool)
  File "/app/./psycopg_pool_cancel_while_waiting.py", line 61, in try_to_get_connection
    async with pool.connection() as connection:
  File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/lib/python3.9/site-packages/psycopg_pool/pool_async.py", line 116, in connection
    conn = await self.getconn(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/psycopg_pool/pool_async.py", line 152, in getconn
    conn = await pos.wait(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/psycopg_pool/pool_async.py", line 670, in wait
    raise self.error
psycopg_pool.PoolTimeout: couldn't get a connection after 2.0 sec
```

**Comment by dvarrazzo** [comment]
Does it mean, basically, that cancelling a coroutine won't honour a `try... finally` or an exit from an `async with` context?

**Comment by Tiendil** [comment]
As I remember from my experiments, the code:

```python

try:
    async with pool.connection() as connection:
        async with connection.cursor() as cursor:
            await cursor.execute('SELECT 1')
            await cursor.fetchall()
except asyncio.CancelledError:
    print('catched!')

```

should catch the cancelled exceptions for coroutines in both states: that are waiting for connection and that have one.

But it seems the pool will not react to this exception.

Also, other exceptions work as expected. The problem is only with cancellation.

Can this be caused by: `Changed in version 3.8: CancelledError is now a subclass of BaseException`?

https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.CancelledError

**Comment by dvarrazzo** [comment]
`connection()` is pretty much a try... finally, so it shouldn't matter the exception class:

https://github.com/psycopg/psycopg/blob/8ca1d4ef95264b32c069eb81ee5f68f1d0c16587/psycopg_pool/psycopg_pool/pool_async.py#L112-L124

Are you able to stick a few logs in that area to see where things don't go as expected?

**Comment by Tiendil** [comment]
See changes here: `https://github.com/Tiendil/psycopg/blob/feature/cancelation-error-experiments/psycopg_pool/psycopg_pool/pool_async.py#L112-L147`

Please tell me if you need to log some specific attribute or something else.

Logs:

```
DEBUG:asyncio:Using selector: EpollSelector
create & open pool
new pool stats:
{'pool_available': 0,
 'pool_max': 3,
 'pool_min': 0,
 'pool_size': 0,
 'requests_waiting': 0}
run a lot of async tasks, part of which will wait for connections
cancel all of them when all available connections taken
DEBUG:psycopg.pool:CONNECTION timeout=None
INFO:psycopg.pool:connection requested from 'test_pool'
INFO:psycopg.pool:growing pool 'test_pool' to 1
DEBUG:psycopg.pool:CONNECTION timeout=None
INFO:psycopg.pool:connection requested from 'test_pool'
DEBUG:psycopg.pool:CONNECTION timeout=None
INFO:psycopg.pool:connection requested from 'test_pool'
DEBUG:psycopg.pool:CONNECTION timeout=None
INFO:psycopg.pool:connection requested from 'test_pool'
DEBUG:psycopg.pool:CONNECTION timeout=None
INFO:psycopg.pool:connection requested from 'test_pool'
DEBUG:psycopg.pool:CONNECTION timeout=None
INFO:psycopg.pool:connection requested from 'test_pool'
DEBUG:psycopg.pool:CONNECTION timeout=None
INFO:psycopg.pool:connection requested from 'test_pool'
INFO:psycopg.pool:adding new connection to the pool
INFO:psycopg.pool:growing pool 'test_pool' to 2
INFO:psycopg.pool:connection given by 'test_pool'
DEBUG:psycopg.pool:CONNECTION conn=<psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff507371370>
DEBUG:psycopg.pool:CONNECTION t0=8410.256317134
DEBUG:psycopg.pool:CONNECTION received <psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff507371370>
INFO:psycopg.pool:adding new connection to the pool
INFO:psycopg.pool:growing pool 'test_pool' to 3
INFO:psycopg.pool:connection given by 'test_pool'
DEBUG:psycopg.pool:CONNECTION conn=<psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff5073713a0>
DEBUG:psycopg.pool:CONNECTION t0=8410.259823842
DEBUG:psycopg.pool:CONNECTION received <psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff5073713a0>
INFO:psycopg.pool:adding new connection to the pool
INFO:psycopg.pool:connection given by 'test_pool'
DEBUG:psycopg.pool:CONNECTION conn=<psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff5073e91f0>
DEBUG:psycopg.pool:CONNECTION t0=8410.263218575
DEBUG:psycopg.pool:CONNECTION received <psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff5073e91f0>
new pool stats:
{'connections_ms': 11,
 'connections_num': 3,
 'pool_available': 0,
 'pool_max': 3,
 'pool_min': 0,
 'pool_size': 3,
 'requests_num': 7,
 'requests_queued': 7,
 'requests_wait_ms': 30,
 'requests_waiting': 4}
Wait the time after which all connections should be available
DEBUG:psycopg.pool:CONNECTION base exception raised CancelledError() for conn <psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff507371370>
DEBUG:psycopg.pool:CONNECTION finally
DEBUG:psycopg.pool:CONNECTION t1=8410.265869095
INFO:psycopg.pool:returning connection to 'test_pool'
DEBUG:psycopg.pool:CONNECTION base exception raised CancelledError() for conn <psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff5073713a0>
DEBUG:psycopg.pool:CONNECTION finally
DEBUG:psycopg.pool:CONNECTION t1=8410.266138119
INFO:psycopg.pool:returning connection to 'test_pool'
DEBUG:psycopg.pool:CONNECTION base exception raised CancelledError() for conn <psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff5073e91f0>
DEBUG:psycopg.pool:CONNECTION finally
DEBUG:psycopg.pool:CONNECTION t1=8410.266387047
INFO:psycopg.pool:returning connection to 'test_pool'
DEBUG:psycopg.pool:CONNECTION putconn called for con <psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff507371370>
DEBUG:psycopg.pool:CONNECTION putconn called for con <psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff5073713a0>
DEBUG:psycopg.pool:CONNECTION putconn called for con <psycopg.AsyncConnection [IDLE] (host=postgres database=default) at 0x7ff5073e91f0>
new pool stats:
{'connections_ms': 11,
 'connections_num': 3,
 'pool_available': 0,
 'pool_max': 3,
 'pool_min': 0,
 'pool_size': 3,
 'requests_num': 7,
 'requests_queued': 7,
 'requests_wait_ms': 96,
 'requests_waiting': 1,
 'usage_ms': 18}
here all connections should be available for usage
=> try to take one connection
DEBUG:psycopg.pool:CONNECTION timeout=None
INFO:psycopg.pool:connection requested from 'test_pool'
Traceback (most recent call last):
  File "/cancelation_error.py", line 113, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/cancelation_error.py", line 109, in main
    await try_to_get_connection(pool)
  File "/cancelation_error.py", line 68, in try_to_get_connection
    async with pool.connection() as connection:
  File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/app/psycopg_pool/psycopg_pool/pool_async.py", line 118, in connection
    conn = await self.getconn(timeout=timeout)
  File "/app/psycopg_pool/psycopg_pool/pool_async.py", line 175, in getconn
    conn = await pos.wait(timeout=timeout)
  File "/app/psycopg_pool/psycopg_pool/pool_async.py", line 693, in wait
    raise self.error
psycopg_pool.PoolTimeout: couldn't get a connection after 2.0 sec
```

**Comment by Tiendil** [comment]
>we give a connection to a cancelled client, and for this reason it gets lost.
It seems you are right.

I made some changes to `_add_to_pool` and `AsyncClient.wait`, and the failed scenario started working.

See changes here: https://github.com/psycopg/psycopg/compare/master...Tiendil:psycopg:feature/cancelation-error-experiments

Changes summary:

- added `cancelled` attribute to `AsyncClient`
- detect `CancelledError` in `AsyncClient.wait` and set `cancelled=True`
- skip cancelled clients in `_add_to_pool`

If it is the right way to fix the issue, I will cleanup the code, add a few tests and make a PR.

Otherwise, I can look deeply into `getconn` logic.

**Comment by dvarrazzo** [comment]
> I made some changes to _add_to_pool and AsyncClient.wait, and the failed scenario started working.

Hey, that's great! It looks like we have found where the problem is :)

I think that we can get away without adding an `AsyncClient.cancelled` attribute. AFAICS the problem comes from an excessively strict error handler here:

https://github.com/psycopg/psycopg/blob/8ca1d4ef95264b32c069eb81ee5f68f1d0c16587/psycopg_pool/psycopg_pool/pool_async.py#L659-L664

Other exceptions fail this and the exception bails out. The Cancelled is probably handled by the asyncio machinery and suppressed, but it leaves the pool in the broken state you have discovered.

Maybe we can do with adding a `BaseException` catch there, and setting `self.error` to whatever raised. In the calling task, the exception will be re-raised a few lines below:

https://github.com/psycopg/psycopg/blob/8ca1d4ef95264b32c069eb81ee5f68f1d0c16587/psycopg_pool/psycopg_pool/pool_async.py#L666-L670

Having set `self.error` will make `set()` return False:

https://github.com/psycopg/psycopg/blob/8ca1d4ef95264b32c069eb81ee5f68f1d0c16587/psycopg_pool/psycopg_pool/pool_async.py#L678-L680

which should make `_add_to_pool()` work as expected, skipping the client which has given up for other reason than a timeout (so the code is correct here, but we need to reword the comment to include other conditions apart from the timeout).

https://github.com/psycopg/psycopg/blob/8ca1d4ef95264b32c069eb81ee5f68f1d0c16587/psycopg_pool/psycopg_pool/pool_async.py#L549-L554

In order to fix the issue, apart from the code fixes, we need to add a test to the test suite.

We also need to run a similar test, and make a similar change, with the sync pool and verify that the issue is not present in the Null variant of the pools (they also employ a clients queue and, even if the pool doesn't have connections in the state, the counter might be thrown off by the error).

Thank you for your tests so far. Would you like to provide a MR with these changes (code, tests) or do you want me to do something too and share the work?

**Comment by Tiendil** [comment]
>Would you like to provide a MR with these changes (code, tests) or do you want me to do something too and share the work?

I would like to make MR, but I can not guarantee that I'll make it soon (I'm going on vacation). 

If there is no time pressure on fixing this bug, I'll do it later. Otherwise not wait for me.

**Comment by dvarrazzo** [comment]
Thank you very much for your help: it was really appreciated! I will try to reproduce the issue in the test suite and fix it as discussed.

**Comment by dvarrazzo** [comment]
Hello @Tiendil!

I've verified that 

```diff
--- a/psycopg_pool/psycopg_pool/pool_async.py
+++ b/psycopg_pool/psycopg_pool/pool_async.py
@@ -640,7 +640,7 @@ class AsyncClient:
 
     def __init__(self) -> None:
         self.conn: Optional[AsyncConnection[Any]] = None
-        self.error: Optional[Exception] = None
+        self.error: Optional[BaseException] = None
 
         # The AsyncClient behaves in a way similar to an Event, but we need
         # to notify reliably the flagger that the waiter has "accepted" the
@@ -662,6 +662,8 @@ class AsyncClient:
                     self.error = PoolTimeout(
                         f"couldn't get a connection after {timeout} sec"
                     )
+                except BaseException as ex:
+                    self.error = ex
 
         if self.conn:
             return self.conn
```

is enough to fix the issue, using your script, but I'm struggling to adapt the test to the test suite. Will merge and make a release fix as soon as I've done that.

**Comment by Tiendil** [comment]
@dvarrazzo thanks!
