### ISSUE TITLE
How to use rowcount and executemany after #479

### ISSUE THREAD

**Issue by djhoese** [psycopg/psycopg#572]
I have a project that uses the below code to insert some records and iterate/generate the results. After #479 the code no longer works for cases where there are no records added. I'm still debugging, but I believe this is the case. I'm wondering if after #479 this snippet of code should be restructured now that `rowcount` has a different value:

```python
    insert_query = INSERT_QUERY.format(table_name)
    cur.executemany(
        insert_query,
        image_record_infos,
        returning=True,
    )
    if not cur.rowcount:
        # no records
        return
    yield from _generate_executemany_results(cur)


def _generate_executemany_results(cur):
    while True:
        for record in cur.fetchall():
            yield record[0]
        if not cur.nextset():
            break
```

CC @dlax author of #479.

**Comment by djhoese** [comment]
Oops should have said this is the error I get:

```
Traceback (most recent call last):
  File "/work/refresh_missing_db_records.py", line 139, in <module>
    sys.exit(main())
  File "/work/refresh_missing_db_records.py", line 53, in main
    publish_amqp_messages(added_file_gen)
  File "/work/refresh_missing_db_records.py", line 129, in publish_amqp_messages
    for amqp_topic, amqp_content in amqp_data_gen:
  File "/work/refresh_missing_db_records.py", line 97, in glob_and_add_files
    all_added_times = sorted(added_gen)
  File "/work/tile_index.py", line 185, in postgres_add_old_missing_files
    for inserted_time in insert_image_records(cur, table_name, row_infos):
  File "/work/postgis_init.py", line 71, in insert_image_records
    yield from _generate_executemany_results(cur)
  File "/work/postgis_init.py", line 76, in _generate_executemany_results
    for record in cur.fetchall():
  File "/usr/local/lib/python3.8/dist-packages/psycopg/cursor.py", line 849, in fetchall
    self._check_result_for_fetch()
  File "/usr/local/lib/python3.8/dist-packages/psycopg/cursor.py", line 596, in _check_result_for_fetch
    raise e.ProgrammingError("no result available")
psycopg.ProgrammingError: no result available
```

**Comment by djhoese** [comment]
Ah, I'm checking for `rowcount` being falsey, but it is initialized/reset to `-1`.

**Comment by dlax** [comment]
@djhoese, can you provide a complete example including the actual query?

**Comment by dvarrazzo** [comment]
As [per spec](https://peps.python.org/pep-0249/#rowcount):

> The attribute is -1 in case no [.execute*()](https://peps.python.org/pep-0249/#id19) has been performed on the cursor or the rowcount of the last operation is cannot be determined by the interface.

Definitely a silly default, but we can't change it without unilaterally breaking the world.
