### ISSUE TITLE
AttributeError: module 'psycopg' has no attribute '_encodings'

### ISSUE THREAD

**Issue by ClodoaldoPinto** [psycopg/psycopg#575]
I'm trying to install `pgAdmin4 7.11` on Centos 8 and I have the error in the title. It was installed with dnf from the official pgAdmin repo.
```
[Mon May 29 14:52:08.440076 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782] mod_wsgi (pid=42691): Failed to exec Python script file '/usr/pgadmin4/web/pgAdmin4.wsgi'.
[Mon May 29 14:52:08.440128 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782] mod_wsgi (pid=42691): Exception occurred processing WSGI script '/usr/pgadmin4/web/pgAdmin4.wsgi'.
[Mon May 29 14:52:08.440641 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782] Traceback (most recent call last):
[Mon May 29 14:52:08.440682 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]   File "/usr/pgadmin4/web/pgAdmin4.wsgi", line 38, in <module>
[Mon May 29 14:52:08.440689 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]     from pgAdmin4 import app as application
[Mon May 29 14:52:08.440702 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]   File "/usr/pgadmin4/web/pgAdmin4.py", line 102, in <module>
[Mon May 29 14:52:08.440708 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]     app = create_app()
[Mon May 29 14:52:08.440719 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]   File "/usr/pgadmin4/web/pgadmin/__init__.py", line 548, in create_app
[Mon May 29 14:52:08.440725 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]     driver.init_app(app)
[Mon May 29 14:52:08.440738 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]   File "/usr/pgadmin4/web/pgadmin/utils/driver/__init__.py", line 27, in init_app
[Mon May 29 14:52:08.440744 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]     DriverRegistry.load_modules(app)
[Mon May 29 14:52:08.440756 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]   File "/usr/pgadmin4/web/pgadmin/utils/driver/registry.py", line 20, in load_modules
[Mon May 29 14:52:08.440776 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]     from . import psycopg3 as module
[Mon May 29 14:52:08.440793 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]   File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg3/__init__.py", line 28, in <module>
[Mon May 29 14:52:08.440800 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]     from .connection import Connection
[Mon May 29 14:52:08.440812 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]   File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg3/connection.py", line 33, in <module>
[Mon May 29 14:52:08.440831 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]     from .cursor import DictCursor, AsyncDictCursor
[Mon May 29 14:52:08.440846 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]   File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg3/cursor.py", line 26, in <module>
[Mon May 29 14:52:08.440852 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]     configure_driver_encodings(encodings)
[Mon May 29 14:52:08.440865 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]   File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg3/encoding.py", line 56, in configure_driver_encodings
[Mon May 29 14:52:08.440879 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782]     psycopg._encodings._py_codecs[key] = python_encoding
[Mon May 29 14:52:08.440903 2023] [wsgi:error] [pid 42691:tid 140022745380608] [remote 179.186.111.77:40782] AttributeError: module 'psycopg' has no attribute '_encodings'
```
Any ideas?

**Comment by dvarrazzo** [comment]
It is a pgadmin issue.
