### ISSUE TITLE
Documentation regarding Ctrl+C and async operations can be cleaned up

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [psycopg/psycopg#599]
Now that https://github.com/psycopg/psycopg/issues/543 has been fixed, I am finding that the documentation at https://www.psycopg.org/psycopg3/docs/advanced/async.html#interrupting-async-operations-using-ctrl-c under "Interrupting async operations using Ctrl-C" is no longer relevant.

Previously, the hacky workaround in the FAQ was necessary in <= 3.1.8 because Ctrl+C would propagate a `CancelledError` instead of the normal `KeyboardInterrupt` in async programs.  However, now that psycopg correctly interprets `CancelledError` as an indication to cancel the query, it is no longer necessary for the user to manually set up these signals.  In fact, in versions >= 3.1.9 it would cause a double cancellation.

This is evidenced in my own program where Ctrl+C during a long running query was observed as follows:
* Version 3.1.8, without the signal handling: the query would continue running on the server even after Python exits!
* Version 3.1.8, with the documented signal handling workaround: the query stops running after Python exits.
* Version 3.1.9, with or without the signal handling: the query stops running after Python exits.

**Proposal:**  Completely delete the "Interrupting async operations using Ctrl-C" section.  Some note could be included in the change log or other upgrade notes to instruct users to consider removing this workaround if they had it from previous versions.

Here's an example traceback from my program; notice how it was CancelledError that was handled by psycopg, not KeyboardInterrupt - this helps prove that #543 fixed the issue:

```
^CTraceback (most recent call last):
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/src/ttmigrate/migrate.py", line 602, in run_command
    await migrator_logic.run_migrations(
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/src/ttmigrate/migrator.py", line 233, in run_migrations
    await self.__apply_migration(
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/src/ttmigrate/migrator.py", line 522, in __apply_migration
    await db_migrations.apply_migration(migration)
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/src/ttmigrate/database.py", line 257, in apply_migration
    await cur.execute(migration.commands)
  File "/Users/james.johnston/Library/Caches/pypoetry/virtualenvs/ttmigrate-E386TQsv-py3.11/lib/python3.11/site-packages/psycopg/cursor_async.py", line 94, in execute
    raise ex.with_traceback(None)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/james.johnston/Library/Caches/pypoetry/virtualenvs/ttmigrate-E386TQsv-py3.11/bin/migrate", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/james.johnston/Thumbtack/postgres-schema/docker/migrate/src/ttmigrate/migrate.py", line 872, in main
    asyncio.run(args.subcommand_function(args))
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/james.johnston/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
```

**Comment by dvarrazzo** [comment]
Thank you for the suggestion! Could you provide a MR go clean up the docs
in a way you would have found useful to read?

Thank you very much!

**Comment by james-johnston-thumbtack** [comment]
@dvarrazzo see how you like #600 !
