### ISSUE TITLE
Django error when using psycopg[binary]

### ISSUE THREAD

**Issue by DenisDudnik** [psycopg/psycopg#661]
I have an error in my docker when I try to build Django 4.2 project with `psycopg[binary]`.
But if I use both of `psycopg `and `psycopg-binary` all works well.

Versions:
```
django==4.2.6
psycopg[binary]==3.1.12 (tryed from 3.1.8 upto 3.1.12) <= this don't work

psycopg==3.1.12               <= this pair work well
psycopg-binary==3.1.12
```

Part of my Docker file:
```
FROM python:3.10-slim as base
ENV PYTHONUNBUFFERED 1 \
    PYTHONDONTWRITEBYTECODE 1 \
    PYTHONFAULTHANDLER=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

FROM base as builder

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gettext \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && rm -rf /var/lib/apt/lists/*
```

Error from Django logs:
```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
     import psycopg as Database
 ModuleNotFoundError: No module named 'psycopg'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 27, in <module>
     import psycopg2 as Database
 ModuleNotFoundError: No module named 'psycopg2'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/app/manage.py", line 31, in <module>
     execute_from_command_line(sys.argv)
   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
     utility.execute()
   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 416, in execute
     django.setup()
   File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
     apps.populate(settings.INSTALLED_APPS)
   File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
     app_config.import_models()
   File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
     self.models_module = import_module(models_module_name)
   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/models.py", line 3, in <module>
     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
   File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 57, in <module>
     class AbstractBaseUser(models.Model):
   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 143, in __new__
     new_class.add_to_class("_meta", Options(meta, app_label))
   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 371, in add_to_class
     value.contribute_to_class(cls, name)
   File "/usr/local/lib/python3.10/site-packages/django/db/models/options.py", line 243, in contribute_to_class
     self.db_table, connection.ops.max_name_length()
   File "/usr/local/lib/python3.10/site-packages/django/utils/connection.py", line 15, in __getattr__
     return getattr(self._connections[self._alias], item)
   File "/usr/local/lib/python3.10/site-packages/django/utils/connection.py", line 62, in __getitem__
     conn = self.create_connection(alias)
   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 193, in create_connection
     backend = load_backend(db["ENGINE"])
   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 113, in load_backend
     return import_module("%s.base" % backend_name)
   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
     raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")
 django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module
```

**Comment by dvarrazzo** [comment]
It sounds pretty unlikely, because the `[binary]` extra just declares a dependency on `psycopg-binary` of the same version.

https://github.com/psycopg/psycopg/blob/4c991e2b7ae70d753c15e43813b6abd15b8e7075/psycopg/setup.py#L30-L33

So I think something else is changing here.

Can you use `pip freeze` and report the differences you see in the envs where you are installing things one way or the other?

Django error just says `ModuleNotFoundError: No module named 'psycopg'` so I think you are not running django in the environment you expect you are.

**Comment by DenisDudnik** [comment]
Yes, `pip freeze` results show a difference. I put here just part about `psycopg`.
When I use:
```
psycopg==3.1.12
psycopg-binary==3.1.12
```

I get:
```
psycopg @ file:///root/wheels/psycopg-3.1.12-py3-none-any.whl
psycopg-binary @ file:///root/wheels/psycopg_binary-3.1.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

```
When I use:
`psycopg[binary]==3.1.12`

I get:
`psycopg @ file:///root/wheels/psycopg-3.1.12-py3-none-any.whl`

**Comment by dvarrazzo** [comment]
What does pip display when you install it?

Do you use pip to install this software or some other tool? Poetry, maybe?

**Comment by DenisDudnik** [comment]
This is a Docker file which is used as a base for Django.
And yes, we use a pip
```
FROM python:3.10.4-slim-bullseye as base
ENV PYTHONUNBUFFERED 1 \
    PYTHONDONTWRITEBYTECODE 1 \
    PYTHONFAULTHANDLER=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

FROM base as builder

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gettext \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && rm -rf /var/lib/apt/lists/*

# Requirements are installed here to ensure they will be cached.
COPY ./requirements /requirements
RUN pip wheel --no-deps --wheel-dir /root/wheels -r /requirements/local.txt


FROM base

COPY ./docker/entrypoint.sh /entrypoint
RUN sed -i 's/\r$//g' /entrypoint && chmod +x /entrypoint

COPY ./docker/start.sh /start
RUN sed -i 's/\r$//g' /start && chmod +x /start

WORKDIR /app
COPY --from=builder /root/wheels /root/wheels
RUN pip install --find-links=/root/wheels/ /root/wheels/*

ENTRYPOINT ["/entrypoint"]

```

**Comment by dvarrazzo** [comment]
You should check the logs during image creation to check why the `[binary]` extra doesn't do what requested.

**Comment by DenisDudnik** [comment]
#13 5.675 Collecting psycopg==3.1.12
#13 5.751   Downloading psycopg-3.1.12-py3-none-any.whl (171 kB)
#13 5.844      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.5/171.5 KB 1.9 MB/s eta 0:00:00
#13 6.256 Collecting psycopg-binary==3.1.12
#13 6.337   Downloading psycopg_binary-3.1.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
#13 7.434      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 3.0 MB/s eta 0:00:00

**Comment by ilBEastli** [comment]
Have the same [binary] issue with local Python (3.11.6 and 3.12 from pyenv), macOS 12.7 and SQLAlchemy 2.0.22

**Comment by DenisDudnik** [comment]
I found a problem line.
`RUN pip wheel --no-deps --wheel-dir /root/wheels -r /requirements/production.txt`
`--no-deps` was a problem.

Thanks for your time.
I close this issue.
