### ISSUE TITLE
pool error: `psycopg.OperationalError: consuming input failed: server closed the connection unexpectedly` when using Aliyun RDS database proxy

### ISSUE THREAD

**Issue by abcfy2** [psycopg/psycopg#731]
Hi there. I'm using Ailyun RDS with a database proxy: https://www.alibabacloud.com/help/en/rds/apsaradb-rds-for-postgresql/what-are-database-proxies

Here's the sample code:

```py
self.__pool = ConnectionPool(
            " ".join("=".join((key, val)) for (key, val) in conn_params.items())
)

# ...
def get_para():
    with self.__pool.connection() as conn:
            with conn.execute(query, params) as cur:
                result = cur.fetchall()
                description = cur.description

#...
```

Worked well for the first while, but after about 6 hours the pool always crash:

```txt
2024-02-04 07:38:32,685 INFO:     [psycopg.pool] - connection requested from 'pool-1'
2024-02-04 07:38:32,685 INFO:     [psycopg.pool] - connection given by 'pool-1'
2024-02-04 07:38:32,686 DEBUG:    [lib.db_service] - executing sql: SELECT DISTINCT ON (FLOOR(timestamp_high / %(interval)s)) "timestamp_high", "ch00_status", "ch01_status", "ch02_stat> ...
2024-02-04 07:38:32,686 INFO:     [psycopg.pool] - returning connection to 'pool-1'
2024-02-04 07:38:32,686 WARNING:  [psycopg.pool] - discarding closed connection: <psycopg.Connection [BAD] at 0x7fd89e435720>
2024-02-04 07:38:32,687 ERROR:    [uvicorn.error] - Exception in ASGI application
Traceback (most recent call last):
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/xg9900-data-service/backend/src/api/xg9900_resource_route.py", line 76, in para_list
    result, _ = db_service.get_para(
  File "/opt/xg9900-data-service/backend/src/lib/db_service.py", line 158, in get_para
    return self.get_para_with_interval(
  File "/opt/xg9900-data-service/backend/src/lib/db_service.py", line 301, in get_para_with_interval
    with conn.execute(query, params) as cur:
  File "/var/lib/xg9900-data-service-backend/venv/lib/python3.10/site-packages/psycopg/connection.py", line 896, in execute
    raise ex.with_traceback(None)
psycopg.OperationalError: consuming input failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

Would you please help? Thanks.

**Comment by dvarrazzo** [comment]
The server you are using is not free software, so we can't support it for free. If you want to pay for consultancy you can reach privately.

**Comment by frankiedrake** [comment]
Same for me. I just can't get it working, continuous errors, such as:  `psycopg.OperationalError: the connection is lost`, `psycopg.OperationalError: consuming input failed: server closed the connection unexpectedly`, `psycopg_pool.PoolTimeout: couldn't get a connection after 30.00 sec`, etc... Seems like it happens, when you a have a class which works with database and you create a variable `self.pool` in, say, `__init__` method, and then use it like `with self.pool.connection()` in a class functions

**Comment by heidar** [comment]
> Same for me. I just can't get it working, continuous errors, such as: `psycopg.OperationalError: the connection is lost`, `psycopg.OperationalError: consuming input failed: server closed the connection unexpectedly`, `psycopg_pool.PoolTimeout: couldn't get a connection after 30.00 sec`, etc... Seems like it happens, when you a have a class which works with database and you create a variable `self.pool` in, say, `__init__` method, and then use it like `with self.pool.connection()` in a class functions


I'm having this problem as well, namely this:
> psycopg.OperationalError: consuming input failed: server closed the connection unexpectedly

I'm using the pool in the same way, copied from the documentation. It uses FastAPI's lifespan of opening a pool on startup and closing it on shutdown. But after some time these errors start happening until I restart the FastAPI server, then it works for a while.

**Comment by dvarrazzo** [comment]
@heidar 

> I'm having this problem as well

As the error says, the server is closing the connection.

You are using an external service you don't have control on, which, in order to scale, will aggressively close seemingly unused connections. You are using the pool, meaning that you want to keep unused connections readily available around. So, you and Bezos have opposite goals.

My suggestion to win this race:

- set a `max_lifetime` short enough to not trigger the problem (10 mins? 30 mins?)
- set up something to run a `select 1` or an empty query regularly (1 min? 30 sec?) against your pool.

For the latter, as most services I write run in k8s, I make use of a k8s [readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) to trigger a database query, so that connections are used also in moments in which the application is less utilized. [fastapi-health](https://github.com/Kludex/fastapi-health) is handy for that:

```python
def instrument_app(app: FastAPI) -> None:
    # Add the /health endpoint
    health_endpoint = health([database_check, ...])
    app.add_api_route("/health", health_endpoint, include_in_schema=False)

async def database_check() -> bool:
    try:
        async with db.pool.connection(timeout=5) as conn:
            await conn.execute("select 1")
        return True
    except Exception as e:
        logger.error("error checking database: %s - %s", type(e).__name__, str(e))
        return False
```

Note that the pool is designed to use the connection in round-robin, not in a stack or in random fashion, therefore you can be sure that calling `connection()` 10 times in a pool of 10 connections you will be served each one exactly once
