### ISSUE TITLE
Unable to connect using sslrootcert=system parameters

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [psycopg/psycopg#928]
Unable to connect using sslrootcert=system parameters. I have set SSL_CERT_FILE env variable. But still getting error.

Code snippet - 
```
from psycopg import connect
import os

if __name__ == '__main__':

    print(os.environ['SSL_CERT_FILE'])

    constr = 'host=<ip> port=<port> dbname=postgres user=postgres password=edb sslmode=verify-full sslrootcert=system'
    db = connect(constr)

    cursor = db.cursor()
    cursor.execute('SELECT table_schema,table_name FROM information_schema.tables ORDER BY table_schema,table_name;')
    rows = cursor.fetchall()
    print(f'{len(rows)} rows returned')
    for row in rows:
        print(row)
    assert len(rows) != 0, 'Should return something'
```

Error -
```
/Users/<user>/.postgresql/root12.crt

Traceback (most recent call last):
  File "/Users/<user>/Library/Application Support/JetBrains/PyCharmCE2021.2/scratches/scratch_9.py", line 10, in <module>
    db = connect(constr)
         ^^^^^^^^^^^^^^^
  File "/Users/<user>/CodingGround/pgAdmin/DevEnv/Venv311/lib/python3.11/site-packages/psycopg/connection.py", line 119, in connect
    raise last_ex.with_traceback(None)
psycopg.OperationalError: connection failed: connection to server at "<ip>", port <port> failed: root certificate file "system" does not exist
Either provide the file or change sslmode to disable server certificate verification.

Process finished with exit code 1
```

However same thing is working with psql - 
```
$ ~ % /Library/PostgreSQL/16/bin/psql "host=<ip>port=<port> dbname=postgres user=postgres connect_timeout=10 sslmode=verify-full sslrootcert=system"
psql (16.4)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.

postgres=# 

````

**Comment by dvarrazzo** [comment]
If you are using `psycopg[binary]`, likely the default path to look for certificates doesn't match the one of your machine. Try specifying `sslrootcert`.

If you install `psycopg[c]` or pure `psycopg`, it will use the system libpq, so its behaviour should be consistent with psql.

More details at https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLROOTCERT

**Comment by yogeshmahajan-1903** [comment]
Just for other - I was using pure psycopg only but pg_config was using Libpq14
