### ISSUE TITLE
Can't instantiate 2 psycopg.Connection objects.

### ISSUE THREAD

**Issue by fabiog1901** [psycopg/psycopg#99]
Ciao Daniele, 

I noticed the below error when testing psycopg3. It worked in psycopg2. The database I'm connecting to is CockroachDB.

```text
fabio@mac: ~/projects/payments $ /usr/local/bin/python3
Python 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg
>>> psycopg.__version__
'3.0.beta1'
>>> dburl = 'postgresql://root@localhost:26257/payments?sslmode=disable'
>>> 
>>> conn = psycopg.connect(dburl)
>>> conn
<psycopg.Connection [IDLE] (host=localhost port=26257 user=root database=payments) at 0x10e131d90>
>>> 
>>> conn2 = psycopg.connect(dburl)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fabio/Library/Python/3.8/lib/python/site-packages/psycopg/connection.py", line 578, in connect
    rv = cls._wait_conn(
  File "/Users/fabio/Library/Python/3.8/lib/python/site-packages/psycopg/connection.py", line 783, in _wait_conn
    return waiting.wait_conn(gen, timeout=timeout)
  File "/Users/fabio/Library/Python/3.8/lib/python/site-packages/psycopg/waiting.py", line 94, in wait_conn
    fileno, s = gen.send(ready)
  File "/Users/fabio/Library/Python/3.8/lib/python/site-packages/psycopg/connection.py", line 414, in _connect_gen
    pgconn = yield from connect(conninfo)
  File "psycopg_binary/_psycopg/generators.pyx", line 48, in connect
psycopg.OperationalError: connection failed: Connection refused
could not send startup packet: Connection refused
>>> 
>>> #######################################################################################
>>> 
>>> import psycopg2
>>> psycopg2.__version__
'2.8.6 (dt dec pq3 ext lo64)'
>>> conn = psycopg2.connect(dburl)
>>> conn2 = psycopg2.connect(dburl)
>>> 
>>> conn
<connection object at 0x10aeebd60; dsn: 'postgresql://root@localhost:26257/payments?sslmode=disable', closed: 0>
>>> conn2
<connection object at 0x10aeebeb0; dsn: 'postgresql://root@localhost:26257/payments?sslmode=disable', closed: 0>
>>> 
```

**Comment by dvarrazzo** [comment]
Ciao Fabio

Uhm... that makes... no sense :sweat_smile:  And is consistently repeatable or it is sporadic/random?

The error seems coming from the server not accepting a connection. Is there any relevant log in the server?

Can you create a libpq connection using `psycopg.pq.PGconn.connect(dburl.encode())`? (similar to what psycopg2 non-async does).

Conversely, if you put psycopg2 in green mode with `psycopg2.extensions.set_wait_callback(psycopg2.extras.wait_select)` can you still connect? (that's similar to what psycopg 3 does).
